/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.java.mini_drive;

import main.java.mini_drive.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App x=new App();
    }
}
